### ISSUE TITLE
cs: `../regexp/compiled/regexp.rktl` target not working

### ISSUE THREAD

**Issue by 97jaz** [racket/racket7#2]
Specifically, when it executes:
```
$(MAKE) bounce BOUNCE_DIR=../regexp BOUNCE_TARGET=regexp-src
```
it just finishes with "make[4]: Nothing to be done for `regexp-src'" without building anything, and "../regexp/compiled" doesn't exist, so the next step, which attempts
```
../../bin/racket convert.rkt ../regexp/compiled/regexp.rktl compiled/regexp.scm
```
fails, because the input file doesn't exist. If I change the BOUNCE_TARGET, above, to `decompile`, then it will create `../regexp/compiled/regexp.rkt` but not the `.rktl` file. The `regexp-src` target doesn't have a definition; it's just listed under `.PHONY`.

**Comment by mflatt** [comment]
Thanks for the repair!
