### ISSUE TITLE
Feature Request : A better REPL experience. 

### ISSUE THREAD

**Issue by abhi18av** [racket/racket7#8]
Hi racket team:) 

I'm really exited and looking forward to the new implementation. So, I thought I might make a wish about a better Repl experience within Racket, which can perhaps build upon  the excellent repl provided by Chez scheme and add a `shell` or `help` mode like the Julia repl, hopefully with a customization settings provided. 

Oh, is there a tentative release date for racket7 ?

**Comment by mflatt** [comment]
Noted!

There's no tentative release date, but things are progressing as expected, so "sometime in the next couple of years" still seems right.
